---
apiVersion: v1
kind: Namespace
metadata:
  name: pds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pds
  namespace: pds
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pds-data"
  namespace: pds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage-retain
---
apiVersion: v1
kind: Service
metadata:
  name: pds
  namespace: pds
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: pds-port
      protocol: TCP
      name: pds-port
  selector:
    app: pds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pds
  namespace: pds
  labels:
    app: pds
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: pds
  template:
    metadata:
      labels:
        app: pds
    spec:
      serviceAccountName: pds
      securityContext:
        fsGroup: 2000
      containers:
        - name: bluesky-pds
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/bluesky-social/pds:0.4.169"
          imagePullPolicy: IfNotPresent
          env:
            - name: PDS_HOSTNAME
              value: nblr.me
            - name: PDS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pds-secret
                  key: jwtSecret
            - name: PDS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pds-secret
                  key: adminPassword
            - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: pds-secret
                  key: plcRotationKey
            - name: PDS_EMAIL_SMTP_URL
              valueFrom:
                secretKeyRef:
                  name: pds-secret
                  key: emailSmtpUrl
            - name: PDS_PORT
              value: "3000"
            - name: PDS_DATA_DIRECTORY
              value: "/pds"
            - name: PDS_BLOBSTORE_DISK_LOCATION
              value: "/pds/blocks"
            - name: PDS_DID_PLC_URL
              value: "https://plc.directory"
            - name: PDS_BSKY_APP_VIEW_URL
              value: "https://api.bsky.app"
            - name: PDS_BSKY_APP_VIEW_DID
              value: "did:web:api.bsky.app"
            - name: PDS_REPORT_SERVICE_URL
              value: "https://mod.bsky.app"
            - name: PDS_REPORT_SERVICE_DID
              value: "did:plc:ar7c4by46qjdydhdevvrndac"
            - name: PDS_CRAWLERS
              value: "https://bsky.network"
            - name: PDS_RATE_LIMITS_ENABLED
              value: "true"
            - name: LOG_ENABLED
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: PDS_EMAIL_FROM_ADDRESS
              value: "admin@nblr.me"
          ports:
            - name: pds-port
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /pds
          livenessProbe:
            httpGet:
              path: /xrpc/_health
              port: pds-port
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "pds-data"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pds
  namespace: pds
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hostnames:
    - nblr.me
    - "*.nblr.me"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway
      namespace: cilium-gateway
  rules:
    - backendRefs:
        - name: pds
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /
