---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-bbcwqx
      protocol: HTTPS
      hostname: bbcwqx.com
      port: 443
      tls:
        certificateRefs:
          - kind: Secret
            name: bbcwqx.com-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: https-nblr
      protocol: HTTPS
      hostname: "*.nblr.app"
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: cloudflare-origin-tls-nblr.app
      allowedRoutes:
        namespaces:
          from: All
